import{a as p,i,S as w}from"./assets/vendor-c493984e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();p.defaults.baseURL="https://pixabay.com";async function f(t,r,o){const l={key:"44562390-aecbf7bf64fbbf331d9c706fa",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o};return(await p.get("/api/",{params:l})).data}function m(t){const r=t.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img
            width="360"
            height="200"
            class="gallery-image"
            src="${o.webformatURL}"
            alt="${o.tags}" />
          <div class="image-info">
            <p>Likes ${o.likes}</p>
            <p>Views ${o.views}</p>
            <p>Comments ${o.comments}</p>
            <p>Downloads ${o.downloads}</p>
          </div>
        </a>
      </li>`).join("");s.imgGallery.insertAdjacentHTML("beforeend",r)}const s={formEl:document.querySelector(".search-form"),imgGallery:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".loadmore-button")};let c="",n=1;const u=15;let y=1;s.formEl.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements.query.value.trim(),c===""){i.warning({title:"Warning",message:"Please, enter the query",layout:2,displayMode:"once",backgroundColor:"#ef4040",position:"topRight"});return}s.imgGallery.innerHTML="",n=1,b();try{const r=await f(c,n,u);if(y=Math.ceil(r.totalHits/u),r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),g();return}m(r.hits),h.refresh(),B(),t.target.reset()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",layout:2,displayMode:"once",backgroundColor:"#ef4040",position:"topRight"})}finally{L()}});s.loadMoreBtn.addEventListener("click",async()=>{if(n>=y){i.error({message:"No more images to load.",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),g();return}n+=1,b();try{const t=await f(c,n,u);if(t.hits.length===0){i.error({message:"Sorry, there are no more images to load.",layout:2,displayMode:"once",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",position:"topRight"}),g();return}m(t.hits),h.refresh()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",layout:2,displayMode:"once",backgroundColor:"#ef4040",position:"topRight"})}finally{L(),M()}});let h=new w(".gallery a",{captionsData:"alt",captionDelay:250});function b(){s.loaderEl.classList.remove("hidden")}function L(){s.loaderEl.classList.add("hidden")}function B(){s.loadMoreBtn.classList.remove("hidden")}function g(){s.loadMoreBtn.classList.add("hidden")}function M(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
